apiVersion: v1
kind: Namespace
metadata:
  name: example

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app1
  namespace: example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: ryutah/app1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        imagePullPolicy: IfNotPresent

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app2
  namespace: example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: ryutah/app2
        ports:
        - containerPort: 8081
        env:
        - name: PROXY_TARGET
          value: app1.example:8080 ## Not required namespace (example) because it is in same namespace.
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
        imagePullPolicy: IfNotPresent

---

kind: Service
apiVersion: v1
metadata:
  name: app1
  namespace: example
spec:
  type: LoadBalancer
  selector:
    app: app1
  ports:
  - name: app1port
    port: 8080
    targetPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: app2
  namespace: example
spec:
  type: LoadBalancer
  selector:
    app: app2
  ports:
  - name: http
    port: 80
    targetPort: 8081

